name: ReUI Prod Preview

on:
  push:
    branches: [nonexistent-branch]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Step 1: Check out the code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Deploy and Restart Application on Server
      - name: Deploy and Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          username: ${{ secrets.SSH_PROD_USER }}
          password: ${{ secrets.SSH_PROD_PSW }}
          port: 22
          script: |
            export PATH=$PATH:/home/faizal/.nvm/versions/node/v20.18.3/bin
            cd /var/www/reui/reui
            git reset --hard
            git pull
            rm -rf node_modules
            rm -rf .next
            npm ci --force || npm install --force
            npm run build || { echo "Build failed, exiting."; exit 1; }
            export PORT=3004
            pm2 restart "reui-web" --update-env || pm2 start npm --name "reui-web" -- start

      # Step 3: Display Deployment Results
      - name: Display Deployment Results
        run: |
          echo "Deployed successfully to https://reui.io"
